#!/usr/bin/env node
'use strict';
/**
 * PDF export smoke test.
 *
 * Zero dependencies, mirrors test/security-test.js's style. Checks the
 * generated bytes are a structurally sane PDF, that ordinary Markdown
 * constructs (headings, lists, code, tables) survive the block parser, and
 * that the one security-relevant bit - link hrefs - reuses safeUrl so a
 * dangerous scheme never reaches a clickable annotation.
 *
 * Run:  node test/pdf-test.js   (also wired into `npm test`)
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const zlib = require('zlib');
const dns = require('dns');
const LIB = path.join(__dirname, '..', 'lib');
const { renderVersionPdf, parseBlocks, wrapTokens, tokenize, textWidth, pdfEscape } = require(LIB + '/pdf');
const { embedPng, embedJpeg, embedImageBytes, isPrivateAddress, safeLookup } = require(LIB + '/pdf-images');
const { createSite } = require(LIB + '/site');
const contentLib = require(LIB + '/content');

let pass = 0;
const failures = [];
const ok = (name, cond) => { if (cond) pass++; else failures.push(name); };

// ── Block parser: the constructs real content actually uses ─────────────────
const blocksOf = md => parseBlocks(md);

ok('heading levels', (() => {
  const b = blocksOf('# One\n## Two\n### Three\n#### Four\n');
  return b.map(x => x.type).join(',') === 'h1,h2,h3,h4';
})());

ok('directive fence dropped, inner prose kept', (() => {
  const b = blocksOf(':::hint type="info"\nHeads up.\n:::\n');
  return b.length === 1 && b[0].type === 'p' && b[0].runs.map(r => r.text).join('') === 'Heads up.';
})());

ok('fenced code block captured verbatim', (() => {
  const b = blocksOf('```csharp\nvar x = 1;\n```\n');
  return b.length === 1 && b[0].type === 'code' && b[0].text === 'var x = 1;';
})());

ok('list items with indent', (() => {
  const b = blocksOf('- one\n- two\n');
  return b.length === 2 && b.every(x => x.type === 'li' && x.indent === 0);
})());

ok('table header + rows', (() => {
  const b = blocksOf('| A | B |\n|---|---|\n| 1 | 2 |\n');
  return b.length === 1 && b[0].type === 'table' && b[0].header.length === 2 && b[0].rows.length === 1;
})());

ok('blockquote', blocksOf('> a note\n')[0].type === 'quote');

// ── Inline styling survives into wrap tokens ─────────────────────────────────
ok('bold/code/link runs tokenized', (() => {
  const b = blocksOf('Some **bold** and `code` and [a link](https://example.com/x).\n');
  const runs = b[0].runs;
  return runs.some(r => r.bold) && runs.some(r => r.code) && runs.some(r => r.url === 'https://example.com/x');
})());

// ── Word wrap actually wraps and never overflows the given width ────────────
ok('wrapTokens fits width, wraps long text', (() => {
  const runs = [{ text: 'word '.repeat(80).trim() }];
  const lines = wrapTokens(tokenize(runs), 200, 10.5);
  if (lines.length < 2) return false;
  return lines.every(line => {
    let w = 0;
    for (const t of line) if (!t.space) w += textWidth(t.text, 10.5, t.style);
    return w <= 200 + 1e-6;
  });
})());

// Regression: wrapTokens must keep space tokens for drawing, not just for the
// wrap-width sum, or every word in a line renders glued to the next.
ok('wrapTokens preserves inter-word spaces within a line', (() => {
  const lines = wrapTokens(tokenize([{ text: 'alpha beta gamma' }]), 400, 10.5);
  return lines.length === 1 && lines[0].filter(t => t.space).length === 2;
})());

// Regression: a typographic character (bullet, smart quote, dash, ellipsis)
// must escape to its single WinAnsi BYTE, not its raw multi-digit Unicode
// code point - the latter overflows a PDF string's 3-digit \ddd octal escape
// and corrupts the stream (observed as garbage text before the fix).
ok('bullet escapes to a single 3-digit octal byte', pdfEscape('•') === '\\225');
ok('smart quotes/em-dash/ellipsis all escape to single bytes', (() => {
  return ['‘', '’', '“', '”', '–', '—', '…']
    .every(ch => /^\\[0-7]{3}$/.test(pdfEscape(ch)));
})());
ok('unmapped non-Latin1 character falls back to ?, no octal overflow', pdfEscape('中') === '?');

// ── Image decoding: synthetic bytes, no network (see pdf-images.js for the
// network fetch itself - SSRF guards are exercised directly below instead) ─

function pngChunk(type, data) {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length, 0);
  return Buffer.concat([len, Buffer.from(type, 'latin1'), data, Buffer.alloc(4)]); // CRC unchecked by our decoder
}

/** A minimal, real, colorType-2 (RGB) PNG: a small solid-but-varying grid so unfiltering is actually exercised. */
function makeRgbPng(width, height, rgbAt) {
  const stride = width * 3;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0; // filter type: None
    for (let x = 0; x < width; x++) {
      const [r, g, b] = rgbAt(x, y);
      const off = y * (stride + 1) + 1 + x * 3;
      raw[off] = r; raw[off + 1] = g; raw[off + 2] = b;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0); ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; ihdr[9] = 2; // 8-bit, colorType 2 (truecolor)
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  return Buffer.concat([sig, pngChunk('IHDR', ihdr), pngChunk('IDAT', zlib.deflateSync(raw)), pngChunk('IEND', Buffer.alloc(0))]);
}

function makeJpegHeader(width, height, components) {
  const compBytes = [];
  for (let i = 0; i < components; i++) compBytes.push(i + 1, 0x11, 0);
  const sof = Buffer.from([
    0xFF, 0xC0, 0x00, 2 + 1 + 2 + 2 + 1 + compBytes.length,
    8, (height >> 8) & 0xFF, height & 0xFF, (width >> 8) & 0xFF, width & 0xFF, components, ...compBytes,
  ]);
  return Buffer.concat([Buffer.from([0xFF, 0xD8]), sof, Buffer.from([0xFF, 0xD9])]);
}

ok('embedPng decodes width/height/colorspace and round-trips pixel bytes', (() => {
  const png = makeRgbPng(4, 3, (x, y) => [x * 50, y * 60, 128]);
  const info = embedPng(png);
  if (!info || info.width !== 4 || info.height !== 3 || info.colorSpace !== '/DeviceRGB' || info.filter !== '/FlateDecode') return false;
  const pixels = zlib.inflateSync(info.data);
  for (let y = 0; y < 3; y++) for (let x = 0; x < 4; x++) {
    const off = (y * 4 + x) * 3;
    if (pixels[off] !== x * 50 || pixels[off + 1] !== y * 60 || pixels[off + 2] !== 128) return false;
  }
  return true;
})());

ok('embedPng splits an alpha channel (colorType 6) into a separate SMask', (() => {
  const width = 3, height = 2, channels = 4;
  const stride = width * channels;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0; // filter: None
    for (let x = 0; x < width; x++) {
      const off = y * (stride + 1) + 1 + x * 4;
      raw[off] = x * 10; raw[off + 1] = y * 20; raw[off + 2] = 200; raw[off + 3] = x === 0 ? 0 : 255; // alpha varies
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0); ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; ihdr[9] = 6; // 8-bit, colorType 6 (truecolor + alpha)
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const png = Buffer.concat([sig, pngChunk('IHDR', ihdr), pngChunk('IDAT', zlib.deflateSync(raw)), pngChunk('IEND', Buffer.alloc(0))]);

  const info = embedPng(png);
  if (!info || !info.smaskData || info.colorSpace !== '/DeviceRGB') return false;
  const color = zlib.inflateSync(info.data);
  const alpha = zlib.inflateSync(info.smaskData);
  for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) {
    const c = (y * width + x) * 3;
    if (color[c] !== x * 10 || color[c + 1] !== y * 20 || color[c + 2] !== 200) return false;
    if (alpha[y * width + x] !== (x === 0 ? 0 : 255)) return false;
  }
  return true;
})());

ok('embedJpeg reads dimensions/components, passes bytes through unchanged', (() => {
  const buf = makeJpegHeader(800, 600, 3);
  const info = embedJpeg(buf);
  return !!info && info.width === 800 && info.height === 600 && info.colorSpace === '/DeviceRGB' && info.filter === '/DCTDecode' && info.data === buf;
})());

ok('embedImageBytes sniffs by magic bytes, not a claimed extension', (() => {
  const png = embedImageBytes(makeRgbPng(2, 2, () => [1, 2, 3]));
  const jpg = embedImageBytes(makeJpegHeader(10, 10, 1));
  const unknown = embedImageBytes(Buffer.from('GIF89a', 'latin1'));
  return png && png.colorSpace === '/DeviceRGB' && jpg && jpg.colorSpace === '/DeviceGray' && unknown === null;
})());

// ── SSRF guard: every resolved address class an attacker-supplied image URL
// could try to reach must be classified correctly ───────────────────────────
ok('SSRF guard rejects private/loopback/link-local IPv4', ['127.0.0.1', '10.1.2.3', '172.16.0.1', '192.168.1.1', '169.254.1.1', '0.0.0.0']
  .every(a => isPrivateAddress(a, 4)));
ok('SSRF guard allows public IPv4', ['8.8.8.8', '1.1.1.1', '93.184.216.34'].every(a => !isPrivateAddress(a, 4)));
ok('SSRF guard rejects loopback/link-local/unique-local IPv6', ['::1', 'fe80::1', 'fc00::1', 'fd12::1'].every(a => isPrivateAddress(a, 6)));
ok('SSRF guard allows public IPv6', !isPrivateAddress('2606:4700:4700::1111', 6));

// Regression: Node's http(s) client calls the custom `lookup` option with
// `all: true` under Happy Eyeballs and expects the full address array back;
// answering with a single (address, family) instead breaks Node's internal
// handling ("Invalid IP address: undefined") well before our own code ever
// sees a response. Exercise the same dual contract dns.lookup itself has.
ok('safeLookup honors options.all (array) vs. single-address callback shapes', (() => {
  let sawArray = false, sawSingle = false;
  const orig = dns.lookup;
  dns.lookup = (hostname, opts, cb) => cb(null, [{ address: '93.184.216.34', family: 4 }]);
  try {
    safeLookup('example.com', { all: true }, (err, result) => { sawArray = !err && Array.isArray(result); });
    safeLookup('example.com', { all: false }, (err, address, family) => { sawSingle = !err && address === '93.184.216.34' && family === 4; });
  } finally { dns.lookup = orig; }
  return sawArray && sawSingle;
})());

// ── End-to-end: a tiny site renders to a structurally valid, non-empty PDF ──
async function main() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'zpdftest-'));
  try {
    fs.mkdirSync(path.join(dir, 'content', 'v1'), { recursive: true });
    fs.writeFileSync(path.join(dir, 'content', 'v1', 'index.md'),
      '---\ntitle: "Home"\n---\n# Home\n\nWelcome. See the [docs site](https://example.com) or '
      + '[click here](javascript:alert(1)).\n\n```js\nconsole.log("hi");\n```\n');
    // enough pages to force the contents list onto more than a trivial layout
    for (let i = 0; i < 3; i++) {
      fs.writeFileSync(path.join(dir, 'content', 'v1', `page${i}.md`), `# Page ${i}\n\nBody text for page ${i}.\n`);
    }
    fs.writeFileSync(path.join(dir, 'docs.config.json'), JSON.stringify({ title: 'Test Docs', versions: ['v1'], defaultVersion: 'v1' }));

    const site = createSite(dir);
    const config = site.loadConfig();
    const buf = await renderVersionPdf(site, config, 'v1', contentLib.listPages);
    const text = buf.toString('latin1');

    ok('starts with %PDF header', text.startsWith('%PDF-1.4'));
    ok('ends with %%EOF', text.trimEnd().endsWith('%%EOF'));
    ok('has a Catalog and Pages object', /\/Type\s*\/Catalog/.test(text) && /\/Type\s*\/Pages/.test(text));
    ok('has at least 5 page objects (title + toc + 4 docs)', (text.match(/\/Type\s*\/Page\b/g) || []).length >= 5);
    ok('non-trivial size', buf.length > 1000);

    // Security: the javascript: link must never become a clickable URI action.
    ok('javascript: href never reaches a Link annotation', !text.includes('/URI (javascript'));
    // The legitimate https link should.
    ok('https link becomes a Link annotation', text.includes('/URI (https://example.com)'));
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }

  const total = pass + failures.length;
  console.log(`\n  PDF suite: ${pass}/${total} passed`);
  if (failures.length) {
    console.log('\n  FAILED:');
    for (const f of failures) console.log(`    ✖ ${f}`);
    console.log('');
    process.exit(1);
  }
  console.log('  ✓ all checks passed\n');
}

main();
